suitecrm:
  build: 7.2.2
  ports:
    - "8080:80"
  links:
    - db:mysql
  environment:
    VIRTUAL_HOST: suitecrm.dev

dbdata:
  image: alpine
  volumes:
    - /var/lib/mysql
  command: true

db:
  image: mariadb
  volumes_from:
    - dbdata
  environment:
    MYSQL_ROOT_PASSWORD: CjTk6WN5qCgE
    MYSQL_DATABASE: suitecrm
    MYSQL_USER: suitecrm
    MYSQL_PASSWORD: 08iBy3UYsnXZ